kind: Service
apiVersion: v1
metadata:
  name: ecm-sb-GIT_BRANCH_NAME
spec:
  ports:
    - name: http-ecm-sb-GIT_BRANCH_NAME
      port: 80
      targetPort: 8080
  selector:
    app: ecm-sb-GIT_BRANCH_NAME