kind: Service
apiVersion: v1
metadata:
  name: documents-GIT_BRANCH_NAME
spec:
  ports:
    - name: http-documents-GIT_BRANCH_NAME
      port: 80
      targetPort: 8080
  selector:
    app: documents-GIT_BRANCH_NAME
