kind: Service
apiVersion: v1
metadata:
  name: scm-sb-GIT_BRANCH_NAME
spec:
  ports:
    - name: http-scm-sb-GIT_BRANCH_NAME
      port: 80
      targetPort: 8080
  selector:
    app: scm-sb-GIT_BRANCH_NAME
